services:
  postgres:
    image: 'postgres:15.4-alpine'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=orderhere'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=orderhere'
#      - 'RABBITMQ_DEFAULT_USER=rabbitmq'
#    ports:
#      - '5672:5672'